<a href="https://colab.research.google.com/github/data-shkim/book-self-study-ml-dl/blob/main/%ED%98%BC%EC%9E%90%EA%B3%B5%EB%B6%80%ED%95%98%EB%8A%94%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D%2B%EB%94%A5%EB%9F%AC%EB%8B%9D_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')

wine.head()

   alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [ ]:
wine.info() # 6,497개의 데이터가 있고, non-null count가 6,497개 있으므로 누락된 값이 없음

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB

In [ ]:
wine.describe()

           alcohol        sugar           pH        class
count  6497.000000  6497.000000  6497.000000  6497.000000
mean     10.491801     5.443235     3.218501     0.753886
std       1.192712     4.757804     0.160787     0.430779
min       8.000000     0.600000     2.720000     0.000000
25%       9.500000     1.800000     3.110000     1.000000
50%      10.300000     3.000000     3.210000     1.000000
75%      11.300000     8.100000     3.320000     1.000000
max      14.900000    65.800000     4.010000     1.000000

In [ ]:
data = wine[['alcohol', 'sugar', 'pH']]
target = wine[['class']]

In [ ]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size = 0.2, random_state=42)
print(train_input.shape, test_input.shape)
print(6497*0.2) # 전체의 20% 를 테스트 데이터로

(5197, 3) (1300, 3)
1299.4

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

print(test_scaled)
print(sum(test_scaled))
print(len(test_scaled[0]))

[[ 1.44082714  1.52797084  0.26967864]
 [-0.48990299 -0.68214836  0.3323304 ]
 [ 1.27293756  0.40206106 -0.23153545]
 ...
 [ 1.60871671 -0.76554908 -0.16888369]
 [-0.90962693  0.88161523  0.52028568]
 [-1.49724045  2.09092573 -1.98578474]]
[ 44.71861889 -38.51367265  62.88534543]
3

In [ ]:
from sklearn.linear_model import LogisticRegression
import numpy as np

lr = LogisticRegression()
lr.fit(train_scaled, np.array(train_target).ravel())
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

# print(np.array(test_target))
# print(np.array(test_target).ravel())

# DataCoversionWarning : 1차원 배열을 기대하는데 2차원 배열을 넘겨서 발생 -> ravel() 로 1차원 배열로 변경
# /usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

0.7808350971714451
0.7776923076923077

In [ ]:
print(lr.coef_, lr.intercept_)

[[ 0.51268071  1.67335441 -0.68775646]] [1.81773456]

In [ ]:
# 결정트리(Decision Tree): 위와 같이 계수와 절편으로 설명하는 것이 아닌 데이터를 나누는 조건으로 트리 구조로 데이터를 나누어감
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(train_scaled, train_target)
print(dt.score(train_scaled, train_target))
print(dt.score(test_scaled, test_target))
# train score 가 많이 높고 test score 가 낮음 => 과대적합

0.996921300750433
0.8592307692307692

In [ ]:
import matplotlib.pyplot as plt
from sklearn.tree import plot_tree
plt.figure(figsize=(10,7))
plot_tree(dt)
plt.show()

KeyboardInterrupt:

In [ ]:
plt.figure(figsize=(10, 7))
plot_tree(dt, max_depth=2, filled=True, feature_names=['alcohol', 'sugar', 'pH'])
plt.show()

In [ ]:
# gini(Gini impurity): 지니 불순도
# = 1 - (음성클래스비율^2 + 양성클래스비율^2)
# 한쪽으로 치우치면 0에 가까워지고 판단할 수 없는 경우는 0.5 (반반)
# 부모의 불순도 - {(왼쪽노드샘플수 / 부모샘플수) * (왼쪽노드불순도) + (오른쪽노드샘플수 / 부모샘플수) * (오른쪽노드불순도)} = 정보이득(information gain)

In [ ]:
dt = DecisionTreeClassifier(max_depth=3, random_state=42)
dt.fit(train_scaled, train_target)
print(dt.score(train_scaled, train_target))
print(dt.score(test_scaled, test_target))

In [ ]:
dt = DecisionTreeClassifier(max_depth=3, random_state=42)
dt.fit(train_input, train_target)
print(dt.score(train_input, train_target))
print(dt.score(test_input, test_target))
print(dt.feature_importances_)  # 특성 중요도

plt.figure(figsize=(20, 15))
plot_tree(dt, filled=True, feature_names=['alcohol', 'sugar', 'pH'])
plt.show()

# 표준화를 하지 않아도 같은 결과 반환, 표준화하지 않아서 트리를 이해하기 더 쉬움

In [ ]:
dt = DecisionTreeClassifier(min_impurity_decrease=0.0005, random_state=42)
dt.fit(train_input, train_target)
print(dt.score(train_input, train_target))
print(dt.score(test_input, test_target))
# plt.figure(figsize=(20,15))
# plot_tree(dt, filled=True, feature_names=['alcohol', 'sugar', 'pH'])
# plt.show()

# min_impurity_decrease=0.0005 성능은 max_depth=3 으로 했을 때 보다 좋음

In [ ]:
import pandas as pd
wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol', 'sugar', 'pH']]
target = wine['class']

In [ ]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)
print(train_input.shape, test_input.shape)
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, test_size=0.2, random_state=42)
print(sub_input.shape, val_input.shape)
# sub_input: 4157, val_input: 1040, test_input: 1300

(5197, 3) (1300, 3)
(4157, 3) (1040, 3)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)

print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

0.9971133028626413
0.864423076923077

In [ ]:
# k-폴드 교차 검증: 훈련 세트를 k 부분으로 나눠서 교차 검증 수행 => 데이터의 8-90%까지 훈련에 사용 가능
from sklearn.model_selection import cross_validate
scores = cross_validate(dt, train_input, train_target)
print(scores)

{'fit_time': array([0.01096296, 0.01016092, 0.01238847, 0.01049852, 0.00970531]), 'score_time': array([0.00232363, 0.00237298, 0.0025332 , 0.00228643, 0.00239921]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [ ]:
import numpy as np
print(np.mean(scores['test_score']))

0.855300214703487

In [ ]:
from sklearn.model_selection import StratifiedKFold # 분류 모델일 경우 타깃 클래스를 골고루 나누기 위해 StratifiedKFold, 회귀일 경우 KFold
scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
print(np.mean(scores['test_score']))

0.855300214703487

In [ ]:
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)
print(np.mean(scores['test_score']))

0.8574181117533719

In [ ]:
# GridSearchCV: 하이퍼파라미터 탐색, 교차검증
from sklearn.model_selection import GridSearchCV
params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=1) # min_impurity_decrease 마다, fold 마다 => 5*5
gs.fit(train_input, train_target) # 자동으로 교차 검증 점수가 가장 높은 매개변수 조합으로 전체 훈련세트에서 다시 모델 훈련

dt = gs.best_estimator_
print(dt.score(train_input, train_target))
print(gs.best_params_)

0.9615162593804117
{'min_impurity_decrease': 0.0001}

In [ ]:
print(gs.cv_results_['mean_test_score'])  # 각 매개변수에서 수행한 교차검증의 평균 점수
print(gs.cv_results_['params'][gs.best_index_]) # 교차검증 평균 점수가 가장 높은 매개변수 조합

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]
{'min_impurity_decrease': 0.0001}

In [ ]:
params = {
    'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001), # 원소 9개
    'max_depth': range(5, 20, 1), # 15개
    'min_samples_split': range(2, 100, 10)  # 10개
}
# 9 * 15 * 10 * k = 1350 * k

In [ ]:
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [ ]:
print(gs.best_params_)
print(np.max(gs.cv_results_['mean_test_score']))

{'max_depth': 14, 'min_impurity_decrease': np.float64(0.0004), 'min_samples_split': 12}
0.8683865773302731

In [ ]:
# random search: 매개변수 값이 수치일 때 값의 범위나 간격을 미리 정하기 어려움, 너무 많은 매개변수 조건이 있어서 시간이 오래 걸릴 수 있음, 목록 대신 확률 분포 전달
from scipy.stats import uniform, randint

rgen = randint(0, 10)
rgen.rvs(10)
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 79, 121, 109,  94,  88, 110,  96,  97, 102, 104]))

In [ ]:
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.99279973, 0.84600832, 0.19246734, 0.85884952, 0.2888063 ,
       0.70050541, 0.24073629, 0.66064986, 0.81519435, 0.88623714])

In [ ]:
params = {
    'min_impurity_decrease': uniform(0.0001, 0.001),
    'max_depth': randint(20, 50),
    'min_samples_split': randint(2, 25),
    'min_samples_leaf': randint(1, 25)
}

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42, splitter='random'), params, n_iter=100, n_jobs=-1, random_state=42)
rs.fit(train_input, train_target)

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42,
                                                    splitter='random'),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7d9cf07553a0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7d9cf0d14290>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7d9cf0757ad0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7d9cf0754bf0>},
                   random_state=42)

In [ ]:
print(rs.best_params_)
print(np.max(rs.cv_results_['mean_test_score']))

dt = rs.best_estimator_
print(dt.score(test_input, test_target))

{'max_depth': 43, 'min_impurity_decrease': np.float64(0.00011407982271508446), 'min_samples_leaf': 19, 'min_samples_split': 18}
0.8458726956392981
0.786923076923077

In [2]:
# 정형 데이터에서 가장 뛰어난 성과를 내는 알고리즘이 '앙상블 학습' 이고, '랜덤 포레스트'가 '앙상블 학습'의 한 종류
# 부트스트랩 샘플: 1000개의 샘플이 들어있는 가방에서 100개의 샘플을 뽑는다면, 먼저 1개 뽑고 다시 가방에 넣고 계속해서 100개를 뽑으면 중복된 샘플을 뽑을 수 있음

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

wine = pd.read_csv('https://bit.ly/wine_csv_data')
data = wine[['alcohol','sugar','pH']]
target = wine['class']
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42)

In [4]:
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9973541965122431 0.8905151032797809

In [6]:
rf.fit(train_input, train_target)
print(rf.feature_importances_)

[0.23167441 0.50039841 0.26792718]

In [8]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.8934000384837406

In [10]:
# 엑스트라 트리: 부트스트랩 샘플을 사용하지 않고 전체 훈련 세트를 사용, 노드를 분할할 때 무작위로 분할
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1,random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9974503966084433 0.8887848893166506

In [13]:
et.fit(train_input, train_target)
print(et.feature_importances_)

[0.20183568 0.52242907 0.27573525]

In [17]:
# 그래디언트 부스팅: 깊이가 얕은 결정 트리를 사용해 이전 트리의 오차를 보완
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42) # 결정 트리 개수를 100 -> 500 으로 늘림
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.8881086892152563 0.8720430147331015
0.9464595437171814 0.8780082549788999

In [18]:
gb.fit(train_input, train_target)
print(gb.feature_importances_)

[0.15887763 0.6799705  0.16115187]

In [21]:
# 히스토그램 기반 그래디언트 부스팅: 입력 특성을 256개 구간으로 나누고, 노드를 분할할 때 최적의 분할을 매우 빠르게 찾을 수 있음
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9321723946453317 0.8801241948619236

In [24]:
from sklearn.inspection import permutation_importance

hgb.fit(train_input, train_target)
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean) # 특성 중요도, 평균, 표준편차

result = permutation_importance(hgb, test_input, test_target, n_repeats=10, random_state=42, n_jobs=-1)
print(result.importances_mean)

hgb.score(test_input, test_target)

[0.08876275 0.23438522 0.08027708]
[0.05969231 0.20238462 0.049     ]

0.8723076923076923

In [26]:
from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.9572351925731766 0.8781988968682904

In [27]:
from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']), np.mean(scores['test_score']))

0.935828414851749 0.8801251203079884